name: contractgen

services:
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    # The image's ENTRYPOINT is "ollama"; we only need to pass the subcommand:
    command: ["serve"]

  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_started
      ollama:
        condition: service_started
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PROVIDER=ollama
      - MODEL=mistral:7b
      - OLLAMA_HOST=http://ollama:11434
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    # No need to mount the Redis data volume to the API container
    ports:
      - "8000:8000"
    restart: unless-stopped

  client:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: client.Dockerfile
    depends_on:
      api:
        condition: service_started
    environment:
      - API_URL=http://api:8000
    volumes:
      - ./client:/app/client
    # Keep the container running
    command: ["tail"]

volumes:
  redis_data:
  ollama_data:
