name: contractgen

services:
  db:
    image: alpine:3.20
    command:
      [
        "/bin/sh",
        "-c",
        "mkdir -p /data && touch /data/contracts.db && tail -f /dev/null",
      ]
    volumes:
      - contracts_data:/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    healthcheck:
      test:
        [
          "CMD",
          "bash",
          "-lc",
          "curl -sf http://localhost:11434/api/tags >/dev/null",
        ]
      interval: 10s
      timeout: 5s
      retries: 30
    entrypoint: ["/bin/sh", "-lc"]
    command: >
      "ollama serve & 
       until curl -sf http://localhost:11434/api/tags >/dev/null; do sleep 1; done;
       ollama pull mistral:7b;
       wait"

  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_started
      ollama:
        condition: service_healthy
    environment:
      - DB_PATH=/data/contracts.db
      - PROVIDER=ollama
      - MODEL=mistral:7b
      - OLLAMA_HOST=http://ollama:11434
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    volumes:
      - contracts_data:/data
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  contracts_data:
  ollama_data:
