name: contractgen

services:
  db:
    image: alpine:3.20
    command:
      [
        "/bin/sh",
        "-c",
        "mkdir -p /data && touch /data/contracts.db && tail -f /dev/null",
      ]
    volumes:
      - contracts_data:/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    # The image's ENTRYPOINT is "ollama"; we only need to pass the subcommand:
    command: ["serve"]

  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_started
      ollama:
        condition: service_started
    environment:
      - DB_PATH=/data/contracts.db
      - PROVIDER=ollama
      - MODEL=mistral:7b
      - OLLAMA_HOST=http://ollama:11434
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    volumes:
      - contracts_data:/data
    ports:
      - "8000:8000"
    restart: unless-stopped
    
  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    depends_on:
      api:
        condition: service_started
    environment:
      - API_URL=http://api:8000
    # Keep the container running
    command: ["tail"]

volumes:
  contracts_data:
  ollama_data:
