name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # This action installs pre-commit and runs it.
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --show-diff-on-failure --color=always --all-files
