name: Lint and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install pipx
          pipx install uv

      - name: Install Deps with uv
        run: uv sync --dev

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit|${{ runner.os }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit hooks
        run: pre-commit run --show-diff-on-failure --color=always --all-files

  unit:
    name: unit
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install pipx
          pipx install uv

      - name: Install Deps with uv
        run: uv sync --dev

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit|${{ runner.os }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit hooks
        run: pre-commit run --show-diff-on-failure --color=always --all-files

      - name: Run unit tests
        run: pytest tests/
